c_compiler_version:
  - 10
cxx_compiler_version:
  - 10
cuda_compiler_version:
  - 12.0
cuda_compiler:
  - cuda-nvcc
fortran_compiler_version:
  - 10
cudnn:
  - 8
cdt_name:
  - cos7
docker_image:
  - quay.io/condaforge/linux-anvil-cos7-x86_64
channel_sources:
  - nvidia,conda-forge
channel_targets:
  - nvidia main
