docker_image:                                # [os.environ.get("BUILD_PLATFORM", "").startswith("linux") or (os.environ.get("CONFIG_VERSION", "1") == "1" and linux)]
   - quay.io/condaforge/linux-anvil-cos7-x86_64    # [os.environ.get("BUILD_PLATFORM") == "linux-64" or (os.environ.get("CONFIG_VERSION", "1") == "1" and linux64)]
   - quay.io/condaforge/linux-anvil-cos7-cuda:9.2        # [linux64 and (os.environ.get("BUILD_PLATFORM") == "linux-64" or os.environ.get("CONFIG_VERSION", "1") == "1")]
   - quay.io/condaforge/linux-anvil-cos7-cuda:10.0       # [linux64 and (os.environ.get("BUILD_PLATFORM") == "linux-64" or os.environ.get("CONFIG_VERSION", "1") == "1")]
   - quay.io/condaforge/linux-anvil-cos7-cuda:10.1       # [linux64 and (os.environ.get("BUILD_PLATFORM") == "linux-64" or os.environ.get("CONFIG_VERSION", "1") == "1")]
   - quay.io/condaforge/linux-anvil-cos7-cuda:10.2       # [linux64 and (os.environ.get("BUILD_PLATFORM") == "linux-64" or os.environ.get("CONFIG_VERSION", "1") == "1")]
   - quay.io/condaforge/linux-anvil-cuda:11.0       # [linux64 and (os.environ.get("BUILD_PLATFORM") == "linux-64" or os.environ.get("CONFIG_VERSION", "1") == "1")]
   - quay.io/condaforge/linux-anvil-cuda:11.1       # [linux64 and (os.environ.get("BUILD_PLATFORM") == "linux-64" or os.environ.get("CONFIG_VERSION", "1") == "1")]
   - quay.io/condaforge/linux-anvil-cuda:11.2       # [linux64 and (os.environ.get("BUILD_PLATFORM") == "linux-64" or os.environ.get("CONFIG_VERSION", "1") == "1")]


c_compiler_version:     # [linux]
  - 7                   # [linux64 or aarch64]
  - 7                   # [linux64 or aarch64]
  - 7                   # [linux64 or aarch64]
  - 7                   # [linux64 or aarch64]
  - 7                   # [linux64 or aarch64]
  - 7                   # [linux64 or aarch64]
  - 7                   # [linux64 or aarch64]
  - 7                   # [linux64 or aarch64]
  - 8                   # [ppc64le]
cxx_compiler_version:   # [linux]
  - 7                   # [linux64 or aarch64]
  - 7                   # [linux64 or aarch64]
  - 7                   # [linux64 or aarch64]
  - 7                   # [linux64 or aarch64]
  - 7                   # [linux64 or aarch64]
  - 7                   # [linux64 or aarch64]
  - 7                   # [linux64 or aarch64]
  - 7                   # [linux64 or aarch64]
  - 8                   # [ppc64le]
fortran_compiler_version:   # [linux]
  - 7                       # [linux64 or aarch64]
  - 7                       # [linux64 or aarch64]
  - 7                       # [linux64 or aarch64]
  - 7                       # [linux64 or aarch64]
  - 7                       # [linux64 or aarch64]
  - 7                       # [linux64 or aarch64]
  - 7                       # [linux64 or aarch64]
  - 7                       # [linux64 or aarch64]
  - 8                       # [ppc64le]

cuda_compiler_version:
  - None                       # [linux64]
  - 9.2                        # [linux64]
  - 10.0                       # [linux64]
  - 10.1                       # [linux64]
  - 10.2                       # [linux64 or win]
  - 11.0                       # [linux64 or win]
  - 11.1                       # [linux64 or win]
  - 11.2                       # [linux64 or win]

cudnn:
  - undefined                  # [linux64]
  - 7                          # [linux64]
  - 7                          # [linux64]
  - 7                          # [linux64]
  - 7                          # [linux64]  # CUDA 10.2
  - 8                          # [win]      # CUDA 10.2
  - 8                          # [linux64 or win]
  - 8                          # [linux64 or win]
  - 8                          # [linux64 or win]

cdt_name:  # [linux]
  - cos7   # [linux64]
  - cos7   # [linux64]
  - cos7   # [linux64]
  - cos7   # [linux64]
  - cos7   # [linux64]
  - cos7   # [linux64]
  - cos7   # [linux64]
  - cos7   # [linux64]
