{% set ucx_version = "1.14.1" %}
{% set number = "0" %}


package:
  name: ucx-split

source:
  url: https://github.com/openucx/ucx/archive/v{{ ucx_version }}.tar.gz
  sha256: e7e82d5812261b5a38f0ba72921b6e0c392f04e2663e740cccbbe11f691880ea

build:
  skip: true  # [not linux or cuda_compiler_version == "None"]
  number: {{ number }}

outputs:
  - name: ucx
    version: {{ ucx_version }}
    build:
      number: {{ number }}
      run_exports:
        - {{ pin_subpackage("ucx", max_pin="x.x") }}
      ignore_run_exports_from:
        - {{ compiler("cuda") }}
    requirements:
      build:
        - {{ compiler("c") }}
        - {{ compiler("cxx") }}
        - {{ compiler("cuda") }}
        - {{ cdt("libnl") }}             # [cdt_name == "cos6"]
        - {{ cdt("libnl3") }}            # [cdt_name == "cos7"]
        - cuda-cudart ={{ cuda_compiler_version }}         # [cuda_compiler_version == "12.0"]
        - cuda-cudart-dev ={{ cuda_compiler_version }}     # [cuda_compiler_version == "12.0"]
        - cuda-cudart-static ={{ cuda_compiler_version }}  # [cuda_compiler_version == "12.0"]
        - cuda-driver-dev ={{ cuda_compiler_version }}     # [cuda_compiler_version == "12.0"]
        - cuda-nvcc ={{ cuda_compiler_version }}           # [cuda_compiler_version == "12.0"]
        - cuda-nvml-dev ={{ cuda_compiler_version }}       # [cuda_compiler_version == "12.0"]
        - automake
        - autoconf
        - libtool
        - make
        - pkg-config
      host:
        - {{ compiler("c") }}
        - {{ compiler("cxx") }}
        - cuda-cudart ={{ cuda_compiler_version }}         # [cuda_compiler_version == "12.0"]
        - cuda-cudart-dev ={{ cuda_compiler_version }}     # [cuda_compiler_version == "12.0"]
        - cuda-cudart-static ={{ cuda_compiler_version }}  # [cuda_compiler_version == "12.0"]
        - cuda-driver-dev ={{ cuda_compiler_version }}     # [cuda_compiler_version == "12.0"]
        - cuda-nvcc ={{ cuda_compiler_version }}           # [cuda_compiler_version == "12.0"]
        - cuda-nvml-dev ={{ cuda_compiler_version }}       # [cuda_compiler_version == "12.0"]
        - libnuma
      run:
    script: install_ucx.sh
    test:
      commands:
        - test -f "${PREFIX}/bin/ucx_info"
        # Requires driver for GPU test.
        # Crashes qemu on ppc64le.
        - ${PREFIX}/bin/ucx_info -v         # [cuda_compiler_version == "None" and not ppc64le]
    about:
      home: https://openucx.org
      license: BSD-3-Clause
      license_family: BSD
      license_file: LICENSE
      summary: Unified Communication X.
      dev_url: https://github.com/openucx/ucx
      doc_url: https://openucx.readthedocs.io/

about:
  home: https://github.com/openucx/ucx
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Unified Communication X.
  dev_url: https://github.com/openucx/ucx
  doc_url: https://openucx.readthedocs.io/

extra:
  recipe-maintainers:
    - Akshay-Venkatesh
    - jakirkham
    - quasiben
    - TomAugspurger
    - leofang
    - matthiasdiener
