{% set ucx_version = "1.14.0" %}
{% set number = "1" %}


package:
  name: ucx-split

source:
  url: https://github.com/openucx/ucx/archive/v{{ ucx_version }}.tar.gz
  sha256: e4ac6561d59653a738f0b73b20f946dd05fa2288ea954659f4a7b6020f994444
  patches:
    - cuda12.patch

build:
  skip: true  # [not linux]
  number: {{ number }}

outputs:
  - name: ucx
    version: {{ ucx_version }}
    build:
      number: {{ number }}
      run_exports:
        - {{ pin_subpackage("ucx", max_pin="x.x") }}
      ignore_run_exports_from:
        - {{ compiler("cuda") }}
    requirements:
      build:
        - {{ compiler("c") }}
        - {{ compiler("cxx") }}
        - {{ compiler("cuda") }}         # [cuda_compiler_version != "12.0"]
        - {{ cdt("libnl") }}             # [cdt_name == "cos6"]
        - {{ cdt("libnl3") }}            # [cdt_name == "cos7"]
        - cuda-cudart ={{ cuda_compiler_version }}        # [cuda_compiler_version == "12.0"]
        - cuda-cudart-dev ={{ cuda_compiler_version }}    # [cuda_compiler_version == "12.0"]
        - cuda-cudart-static ={{ cuda_compiler_version }} # [cuda_compiler_version == "12.0"]
        - cuda-driver-dev ={{ cuda_compiler_version }}    # [cuda_compiler_version == "12.0"]
        - cuda-nvcc ={{ cuda_compiler_version }}          # [cuda_compiler_version == "12.0"]
        - cuda-nvml-dev ={{ cuda_compiler_version }}      # [cuda_compiler_version == "12.0"]
        - automake
        - autoconf
        - libtool
        - make
        - pkg-config
      host:
        - {{ compiler("c") }}
        - {{ compiler("cxx") }}
        - cuda-cudart ={{ cuda_compiler_version }}        # [cuda_compiler_version == "12.0"]
        - cuda-cudart-dev ={{ cuda_compiler_version }}    # [cuda_compiler_version == "12.0"]
        - cuda-cudart-static ={{ cuda_compiler_version }} # [cuda_compiler_version == "12.0"]
        - cuda-driver-dev ={{ cuda_compiler_version }}    # [cuda_compiler_version == "12.0"]
        - cuda-nvcc ={{ cuda_compiler_version }}          # [cuda_compiler_version == "12.0"]
        - cuda-nvml-dev ={{ cuda_compiler_version }}      # [cuda_compiler_version == "12.0"]
        - libnuma
      run:
    script: install_ucx.sh
    test:
      commands:
        - test -f "${PREFIX}/bin/ucx_info"
        # Requires driver for GPU test.
        # Crashes qemu on ppc64le.
        - ${PREFIX}/bin/ucx_info -v         # [cuda_compiler_version == "None" and not ppc64le]
    about:
      home: https://openucx.org
      license: BSD-3-Clause
      license_family: BSD
      license_file: LICENSE
      summary: Unified Communication X.
      dev_url: https://github.com/openucx/ucx
      doc_url: https://openucx.readthedocs.io/

about:
  home: https://github.com/openucx/ucx
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Unified Communication X.
  dev_url: https://github.com/openucx/ucx
  doc_url: https://openucx.readthedocs.io/

extra:
  recipe-maintainers:
    - Akshay-Venkatesh
    - jakirkham
    - quasiben
    - TomAugspurger
    - leofang
    - matthiasdiener
